name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda 1x por dia
  workflow_dispatch:       # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: fiore123
          outputs: |
            # dist/snake.gif
            dist/snake-classic.svg
            dist/snake-area.svg
          color_snake: purple
          color_dots: "#ffffff #9be9a8 #40c463 #30a14e #216e39"
          snake_game: classic

      - name: Generate snake area style
        uses: Platane/snk@v3
        with:
          github_user_name: fiore123
          outputs: dist/snake-area.svg
          color_snake: "#ff6600"
          color_dots: "#ebedf0 #c6e48b #7bc96f #239a3b #196127"
          snake_game: area

      - name: Push Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
