name: Generate Snake

on:
  schedule: # executa automaticamente todo dia
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: fiore123
          outputs: dist/github-contribution-grid-snake.gif
          
      - name: Upload to the repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generate snake animation"
          add: "dist/*.gif"
